# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=browsersync

before_install:
  - docker pull node:alpine

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - docker run -dit --entrypoint=top --name="$DEMYX_REPOSITORY" demyx/"$DEMYX_REPOSITORY"
  - docker exec -t "$DEMYX_REPOSITORY" browser-sync --version

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - bash travis.sh
